/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PolicyEngineWrapper_NXPolicyEngineWrapper */

#ifndef _Included_PolicyEngineWrapper_NXPolicyEngineWrapper
#define _Included_PolicyEngineWrapper_NXPolicyEngineWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PolicyEngineWrapper_NXPolicyEngineWrapper
 * Method:    GetRightsViaJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/HashMap;[BLjava/util/Vector;Ljava/util/Vector;)I
 */
JNIEXPORT jint JNICALL Java_PolicyEngineWrapper_NXPolicyEngineWrapper_GetRightsViaJni
  (JNIEnv *, jclass, jstring, jstring, jobject, jbyteArray, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
